// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASN9fWXsjJ0hewpo0CpUSLdK0CZ2ceCko',
    appId: '1:423847166550:android:5014d53e9a0c80b39531f7',
    messagingSenderId: '423847166550',
    projectId: 'landandplot-v2',
    storageBucket: 'landandplot-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0VpWnObFi5_vD3qDb5DCOW-HL1mfoRss',
    appId: '1:423847166550:ios:b648167e1eaaa2349531f7',
    messagingSenderId: '423847166550',
    projectId: 'landandplot-v2',
    storageBucket: 'landandplot-v2.appspot.com',
    androidClientId: '423847166550-06umbqp3nen07e50a88nhis2hiqhk1io.apps.googleusercontent.com',
    iosClientId: '423847166550-sddpkmpf1knger600lq2c8m04p336kr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.landandplot',
  );

}