import 'package:flutter/material.dart';
import '../components/forms/sell_land_form.dart';
import '../models/property_model.dart';
import '../services/user_service.dart';
import '../services/property_service.dart';
import 'package:firebase_auth/firebase_auth.dart';

class SellLandScreen extends StatefulWidget {
  const SellLandScreen({super.key});

  @override
  _SellLandScreenState createState() => _SellLandScreenState();
}

class _SellLandScreenState extends State<SellLandScreen> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _areaController = TextEditingController();
  final TextEditingController _priceController = TextEditingController();
  final TextEditingController _pricePerSqYardController = TextEditingController();

  @override
  void dispose() {
    _areaController.dispose();
    _priceController.dispose();
    _pricePerSqYardController.dispose();
    super.dispose();
  }

  void _submitForm() async {
    if (_formKey.currentState!.validate()) {
      final user = FirebaseAuth.instance.currentUser;
      if (user != null) {
        Property newProperty = Property(
          id: '', // ID will be generated by Firestore
          userId: user.uid,
          landArea: double.parse(_areaController.text),
          landPrice: double.parse(_priceController.text),
          pricePerSqYard: double.parse(_pricePerSqYardController.text),
        );

        // Save the property using PropertyService
        String propertyId = await PropertyService().addProperty(newProperty);

        // Link the property to the user using UserService
        await UserService().addPropertyToUser(user.uid, propertyId);

        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Property added successfully!')),
        );

        Navigator.pop(context);
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('User not logged in.')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Sell Your Land'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: SellLandForm(
          formKey: _formKey,
          areaController: _areaController,
          priceController: _priceController,
          pricePerSqYardController: _pricePerSqYardController,
          onSubmit: _submitForm,
        ),
      ),
    );
  }
}