import 'package:flutter/material.dart';
import '../components/forms/sell_land_form.dart';
import '../models/property_model.dart';
import '../services/property_service.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class SellLandScreen extends StatefulWidget {
  const SellLandScreen({super.key});

  @override
  SellLandScreenState createState() => SellLandScreenState();
}

class SellLandScreenState extends State<SellLandScreen> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _areaController = TextEditingController();
  final TextEditingController _priceController = TextEditingController();
  final TextEditingController _pricePerSqYardController =
      TextEditingController();

  LatLng? selectedLocation; // Store the selected location

  @override
  void dispose() {
    _areaController.dispose();
    _priceController.dispose();
    _pricePerSqYardController.dispose();
    super.dispose();
  }

  Future<void> _submitForm() async {
    if (_formKey.currentState!.validate()) {
      final user = FirebaseAuth.instance.currentUser;
      if (user != null && selectedLocation != null) {
        Property newProperty = Property(
          id: '', // The ID will be generated by Firestore in PropertyService
          userId: user.uid,
          landArea: double.parse(_areaController.text),
          landPrice: double.parse(_priceController.text),
          pricePerSqYard: double.parse(_pricePerSqYardController.text),
          latitude: selectedLocation!.latitude, // Save the selected latitude
          longitude: selectedLocation!.longitude, // Save the selected longitude
        );

        try {
          // Save the property using PropertyService
          String propertyId = await PropertyService().addProperty(newProperty);

          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Property added successfully!')),
            );
            // Navigate to BuyLandScreen using the named route '/buy_land'
            Navigator.pushReplacementNamed(context, '/buy_land');
          }
        } catch (e) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(content: Text('Failed to add property: $e')),
            );
          }
        }
      } else {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Please select a location')),
          );
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Sell Your Land'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: SellLandForm(
          formKey: _formKey,
          areaController: _areaController,
          priceController: _priceController,
          pricePerSqYardController: _pricePerSqYardController,
          onSubmit: _submitForm,
          onLocationSelected: (LatLng location) {
            setState(() {
              selectedLocation = location; // Store the selected location
            });
          },
        ),
      ),
    );
  }
}
