-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUSzVP5kyDU4NjPv7
GiP/vm8JXd1iSCOARzCTgX1MyjGgCgYIKoZIzj0DAQehRANCAASSMJyjyQy6DfnL
czJwsE07TEGjNo0gYsLygvUuuv8cFhAl/9M/DyHEd8g8J+DlSrBzRaFYEWnEDhx8
Sb8YTuFk
-----END PRIVATE KEY-----